server:
  port: 5005
spring:
  application:
    name: booking-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:mysql://localhost:3306/bookingdb
      username: root
      password: priya_27
      driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

spring.jpa.show-sql: true