server:
  port: 5002
spring:
  application:
    name: salon-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/salondb?createDatabaseIfNotExist=true
    username: root
    password: priya_27
    driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/